apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-rds-pv-volume
  namespace: argocd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
