apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-rds-pv-claim
  namespace: argocd
  labels:
    app: wordpress-rds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
