apiVersion: v1
kind: Secret
metadata:
  name: rds-pass
  namespace: argocd
type: Opaque
data:
  host: ZGV2b3BzaW50ZXJ2aWV3LmN3N3FnazI4Zzl0bC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20K
  dbname: ZGV2b3BzaW50ZXJ2aWV3Cg==
  username: ZGV2b3BzaW50ZXJ2aWV3Cg==
  password: ZDN2MHBzLTFudDNydjEzdwo=
