apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: argocd
  labels:
    app: wordpress-rds
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
